### PR TITLE
Ch refactor to run 164327460

### PR DESCRIPTION
**Pull request by PatrickMugayaJoel**
@bisonlou @kbjude @kalsmic @mwinel @AtamaZack

### CODE REVIEW

**Comment by mwinel** [comment]
This runs the app well and termination is successful.

**Review by mwinel — APPROVED** [review]
This runs the app so well and terminates successfully. This could work as a good basis for the remaining implementations.

**Comment by bisonlou** [comment]
Well dobe Patrick. I have incoporated your changes and everything looks good.

**Review by kalsmic — APPROVED** [review]
Thanks, @PatrickMugayaJoel, let us build on this.

**Pull request merged**
